openedx/frontend-enterprise

src/learnerPortalLinks.js
refer to the new primary/secondary/tertiary branding configuration colors.
=> Rename new branding config field names

src/course-search/data/hooks.js, src/course-search/data/tests/hooks.test.jsx, src/index.js
I have moved the hook to the learner portal, as it is only relevant there; I am exporting it's dependencies from this library
=> Remove unneeded hook

src/course-search/styles/_SearchPagination.scss, src/course-search/styles/_index.scss
=> fix: update pagination styles for use with DataTable

src/course-search/SearchContext.jsx, src/course-search/SearchHeader.jsx, src/course-search/data/constants.js
[ENT-2990](https://openedx.atlassian.net/browse/ENT-2990)
Adds a "Language" facet dropdown to the course search header.
=> feat: add language facet to SearchHeader

src/course-search/data/constants.js
Title / commit message says it all.
[ENT-4460](https://openedx.atlassian.net/browse/ENT-4460)
=> feat: adds typeahead options for subject, partner, program

packages/catalog-search/src/SearchBox.jsx
[Jira](https://openedx.atlassian.net/browse/ENT-4500)
We want to allow for slightly less fragile scripted monitoring systems by adding New Relic specific data attributes that will indicate to devs that changing or removing may cause alerts.
=> maint: adding New Relic data tags for monitoring purposes

packages/catalog-search/src/FacetListBase.jsx
https://user-images.githubusercontent.com/29247391/127161043-633d7e56-51b0-491e-80d2-3b70d31d5629.mov
=> ENT-4651 | added support for `single-item` facetValueType in FacetListBase

packages/catalog-search/README.md
This PR primarily serves as a test for Lerna publishing.
=> fix: update readme

.github/pull_request_template.md, packages/catalog-search/README.md
=> fix: update Algolia link in catalog-search README

packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/catalog-search/src/FacetItem.jsx
- [ x] Ensure your commit message follows the semantic-release conventional commit message format
Screenshot of new alignment and style:
=> style: :lipstick: Fix Facet alignment and styling of badge for 0 results

packages/catalog-search/src/FacetListBase.jsx
[ENT4786](https://openedx.atlassian.net/browse/ENT-4876): This PR is about adding functionality in the current job dropdown where the user can unselect the value he has selected earlier. Previously he can only switch to another value but cannot deselect the value.
=> feat: ENT4876: Added delete functionality in single-item refinement type

packages/catalog-search/src/FacetItem.jsx, packages/catalog-search/src/FacetListBase.jsx
=> fix: show count on dropdown list items only when showBadge is true

packages/catalog-search/package-lock.json, packages/catalog-search/package.json, packages/logistration/package-lock.json, packages/logistration/package.json, packages/utils/package-lock.json, packages/utils/package.json
=> fix: use shared browserslist configuration

packages/catalog-search/src/config/index.js, packages/catalog-search/src/data/constants.js
Reverts edx/frontend-enterprise#181
=> Revert: "ENT-5020 | fix: reverted changes to use program_title and now using program titl…"

packages/catalog-search/src/SearchBox.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/tests/SearchBox.test.jsx
=> fix: Change the Search Box title to include programs

packages/catalog-search/src/SearchBox.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/styles/_CurrentRefinements.scss, packages/catalog-search/src/tests/SearchBox.test.jsx
=> feat: add functionality to hide searchbox header

packages/catalog-search/package-lock.json, packages/logistration/package-lock.json, packages/logistration/package.json
=> fix: remove query-string dependency

packages/catalog-search/src/config/index.js, packages/catalog-search/src/data/tests/utils.test.js, packages/catalog-search/src/data/utils.js, packages/utils/src/index.js, packages/utils/src/tests/utils.test.jsx, packages/utils/src/utils.js
=> feat: add hasFeatureFlagEnabled util function

.gitignore, packages/catalog-search/src/SearchSuggestions.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-5520
Also fixes
=> fix: error autocomplete when authoring_organizations is empty

packages/catalog-search/src/CurrentRefinements.jsx, packages/catalog-search/src/LearningTypeRadioFacet.jsx, packages/catalog-search/src/config/index.js, packages/catalog-search/src/data/constants.js, packages/catalog-search/src/tests/LearningTypeRadioFacet.test.jsx
=> feat: add learning type `Pathways`

packages/catalog-search/src/SearchBox.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/SearchSuggestionItem.jsx, packages/catalog-search/src/SearchSuggestions.jsx, packages/catalog-search/src/data/constants.js, packages/catalog-search/src/data/hooks.js, packages/catalog-search/src/tests/SearchBox.test.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx
This PR:
- allows search header/suggestions to work without an index or enterprise slug
- if index is not provided then suggestions will simply not render
- if enterprise slug is not provided then a new bool prop `disableSuggestionRedirect=true` needs to be provided
- allows the search suggestion component's submit behavior to be overwritten with a function passed in through the search header prop `suggestionSubmitOverride` 
- this function is given the inputs `course title` and the algolia course `hit` object
- tracks the focused element on the page and only displays suggested results when the search header is focused
- This may be …
=> feat: making suggested items backwards compatible and redirect func overridable

.github/workflows/bump-all-major.yml, .github/workflows/ci.yml, .github/workflows/publish-from-package.yml, .github/workflows/release.yml
=> build: use npm ci

packages/utils/src/roles.js, packages/utils/src/tests/roles.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-4182
=> fix: updated enterprise role check for multiple enterprises

package-lock.json, packages/catalog-search/package.json, packages/logistration/package.json, packages/utils/package.json
=> chore: update peer dependency requirement for @edx/frontend-platform

.github/workflows/bump-all-major.yml, .github/workflows/ci.yml, .github/workflows/publish-from-package.yml, .github/workflows/release.yml
Updating codecov action to v3 to keep it in sync with frontend ecosystem.
=> Updated codecov action to v3

packages/catalog-search/src/TypeaheadFacetDropdown.jsx
=> fix: hotfix for explore catalog issue

packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/hotjar/CHANGELOG.md, packages/hotjar/package.json, packages/logistration/CHANGELOG.md, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
- @edx/frontend-enterprise-catalog-search@3.1.7
- @edx/frontend-enterprise-hotjar@1.2.2
- @edx/frontend-enterprise-logistration@2.1.3
- @edx/frontend-enterprise-utils@2.2.2
=> chore(release): publish new versions

packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/hotjar/CHANGELOG.md, packages/hotjar/package.json, packages/logistration/CHANGELOG.md, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
- @edx/frontend-enterprise-catalog-search@3.1.9
- @edx/frontend-enterprise-hotjar@1.2.4
- @edx/frontend-enterprise-logistration@2.1.5
- @edx/frontend-enterprise-utils@2.2.4
=> chore(release): publish new package versions

.github/workflows/ci.yml, .github/workflows/publish-from-package.yml, .github/workflows/release.yml, package-lock.json, package.json
=> Attempt 3 to setup Lerna

lerna.json
=> Update lerna setting useWorkspace to true

.github/workflows/release.yml
=> Try some different lerna version options

.github/workflows/release.yml
=> Add some debug logging for lerna version

packages/catalog-search/src/SearchSuggestions.jsx, packages/catalog-search/src/tests/SearchBox.test.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6670
=> feat: adding exec ed compatibility to suggested search

package-lock.json, packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json
-  @edx/frontend-enterprise-catalog-search@4.3.0
=> chore(release): publish new version of catalog-search.

lerna.json, package-lock.json, packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/logistration/CHANGELOG.md, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> Release new versions 

package-lock.json, packages/hotjar/CHANGELOG.md, packages/hotjar/package.json
=> Release new hotjar version

package-lock.json, packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/logistration/CHANGELOG.md, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
Reverts openedx/frontend-enterprise#368
=> Revert "chore(release): publish new versions "

packages/catalog-search/src/styles/_SearchSuggestions.scss
Fix the margins for when the prequery suggestion is highlighted to match B2C.
https://2u-internal.atlassian.net/browse/ENT-8593
|before|after|
|-------|------|
|![Screenshot 2024-03-07 at 10 26 49 AM](https://github.com/openedx/frontend-enterprise/assets/71999631/502f56b1-7f59-4248-84d4-3a302b1ef371)| ![Screenshot 2024-03-07 at 10 34 06 AM](https://github.com/openedx/frontend-enterprise/assets/71999631/b672c486-c0ba-4fbb-8153-0f9ba4e715e9)|
- *Note*: There may be a slight delay between when the workflow finished and when NPM reports the package …
=> feat: fix prequery suggestion highlight container

packages/catalog-search/src/SearchHeader.jsx
https://2u-internal.atlassian.net/browse/ENT-8859
This PR addresses the requirement for AI Curation, which requires displaying only dropdown filters to further refine the AI Curation results, hiding the search box. 
To meet this requirement, I have implemented a flag that will be passed as a prop whenever AI Curation is enabled. The default value of this prop is set to false, ensuring it does not affect other repositories using this package. As a result, the search box is hidden, and only the dropdown filters are displayed to refine the AI Curation results
- This may be triggered by clicking the "Run workflow" option for the ``master`` …
=> [ENT-8859] Manage visibility of search box via flag prop

packages/catalog-search/src/LearningTypeRadioFacet.jsx, packages/catalog-search/src/SearchContext.jsx, packages/catalog-search/src/config/index.js
**Ticket:**
[ENT-9290](https://2u-internal.atlassian.net/browse/ENT-9290)
**Description:**
Made changes to show the videos learning type only to the enterprise learners who have an active subscription.
=> ENT-9290: Show the video learning type only to the learners who have an active subscription

packages/catalog-search/src/LearningTypeRadioFacet.jsx
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-9383
**Description**
Added `Beta` label to videos in the learning type facet
**UI Screenshot**
=> [ENT-9383] Add Beta label to videos in the learning type facet
