package-lock.json, package.json, src/learnerPortalLinks.js, src/utils.js, webpack.config.js
BREAKING CHANGE: This version requires @edx/frontend-auth v9.0.1 or later.  It is incompatible with prior versions of frontend-auth and will not function.  Because it’s a peer dependency, consumers of this library must provide a compatible version of @edx/frontend-auth.
=> fix: add peer dependency on frontend-auth and upgrade

package.json, src/learnerPortalLinks.js, webpack.config.js
BREAKING CHANGE: getLearnerPortalLinks now requires a user to be passed
in. This is done to remove the dependency on frontend-auth so it can be
used in both edx-platform and other MFEs.
ENT-2648
=> feat: require passing user to learnerPortalLinks

package.json
There was no need to put 2.0.0 in the package json version. Apparently we just leave it at 1.0.0
=> fix: update version number in package.json

src/learnerPortalLinks.js
Example outputs:
```
[
{
title: 'Test Enterprise',
url: 'https://localhost:18000/test-enterprise',
branding_configuration: {
logo: 'http://localhost:18000/media/enterprise/branding/None/None_logo.png',
banner_border_color: '#bbbbbb',
banner_background_color: '#eeeeee'
}
}
]
```
```
[
{
title: 'Test Enterprise',
url: 'https://localhost:18000/test-enterprise',
branding_configuration: null
}
]
```
=> ENT-2893: Adds branding configuration to links

src/constants.js, src/index.js, src/learnerPortalLinks.js, src/utils.js
Used to get the UUID from a user's roles that match `enterprise_learner` as the first matching one is the selected and active enterprise for that user.
Usage example:
```
getLearnerPortalLinks(httpClient, authenticatedUser).then((learnerPortalLinks) => {
const preferredUUID = getPreferredEnterpriseUUID(authenticatedUser);
const preferredLearnerPortalLink = learnerPortalLinks.find(learnerPortalLink => learnerPortalLink.uuid == preferredUUID);
});
```
=> feat: adds function to return the preferred enterprise uuid for a user

.gitignore, package-lock.json, package.json, src/hooks.js, src/index.js
Several of our frontend apps and components require the same enterprise configuration data to fetch a user's learner portal link and make a decision about which dropdown items to show in the header menu:
* https://github.com/edx/frontend-component-header-edx/blob/master/src/data/hooks/enterprise.js
* https://github.com/edx/frontend-app-learning/pull/175
This PR exposes a new enterprise hook that can be used by the above.  It helps us DRY up the code and helps de-couple both of the above from the enterprise ecosystem.
=> feat: expose useEnterpriseConfig hook

package.json, webpack.config.js
react should not be included in the built artifact, even though it's a dev dependency, because this package is installed into applications that install their own react dependency.
Also points webpack output at `dist/index.js` so that our frontend-build library can recognize the local module at the "usual" place: https://github.com/edx/frontend-build#local-module-configuration-for-webpack
=> fix: make react an external during webpack build

package-lock.json, package.json, src/hooks.js, src/learnerPortalLinks.js, src/service.js
Pass the user's "preferred" enterprise uuid to the API call to `/enterprise-customer/` to prevent a paginated response.
**Testing instructions**
1. Install this branch of your local checkout of @edx/frontend-enterprise into a consuming MFE (e.g., frontend-app-learning).
2. Observe a network request to `/enterprise-customer/` which includes the `uuid` query parameter.
=> fix: only fetch user's preferred enterprise metadata

README.rst
Just readme change, prior release for pull/21 did not work due to either github creds or commit related issue. Trying new PR with correctly formatted commit message
=> feat: eslint-plugin-import dependency upgrade

.github/workflows/release.yml
Adding testing step during releases to get coverage for coveralls
Also removed the explicit npm build step as semantic-release already builds
=> fix: Adding testing during release for coveralls

.github/workflows/release.yml
One more try - going to use the github action provided by coveralls
=> chore: Switch coveralls to use official github action

package-lock.json, package.json
Why?
I noted that these two fortawesome libs are used directly by frontend learner portal and are makred as peer deps here but not used within this project. And they are already depended on by FE learner portal. hence they can be safely removed.
These were added in this commit: https://github.com/edx/frontend-enterprise/blob/a461a769faa2766aebe99f6d9de6fb110a54876b/package.json
```
"@fortawesome/fontawesome-svg-core": "^1.2.17",
"@fortawesome/free-brands-svg-icons": "^5.11.2",
"@fortawesome/free-regular-svg-icons": "^5.12.1",
```
but the only one actually used here is `fortawesome/free-solid-svg-icons`
I tested locally by using the new package of frontend-enterprise installed into frontend learner portal
=> feat: ENT-3844 remove extraneous dependencies added during prior work

package-lock.json, package.json
This brings in an upstream fix/contribution to `react-instantsearch-dom` as described here: https://github.com/algolia/react-instantsearch/pull/3003
=> fix: upgrade react-instantsearch-dom to 6.8.3

.github/workflows/ci.yml, src/course-search/ClearCurrentRefinements.jsx, src/course-search/tests/ClearCurrentRefinements.test.jsx
Adds tests to hopefully fix the drop in % test coverage that happened when I removed the hook.
Has coveralls run on PRs, because if it's going to fail the build, I want to know before merge.
=> Add tests and run coveralls on PRs

package-lock.json, package.json, src/course-search/FacetDropdown.jsx, src/course-search/FacetItem.jsx, src/course-search/FacetListBase.jsx, src/course-search/MobileFilterMenu.jsx, src/course-search/SearchFilters.jsx, src/course-search/SearchHeader.jsx, src/course-search/TypeaheadFacetDropdown.jsx, src/course-search/data/constants.js, src/course-search/styles/_FacetList.scss, src/course-search/styles/_MobileSearchFilters.scss, src/course-search/tests/ClearCurrentRefinements.test.jsx, src/course-search/tests/FacetListBase.test.jsx, src/course-search/tests/FacetListRefinement.test.jsx
**Description:** Add a new dropdown with search capability to filter the options. The dropdown will show names of skills offered by courses.
**JIRA:** https://openedx.atlassian.net/browse/ENT-4104
https://user-images.githubusercontent.com/6767924/111488542-2b1c9800-875b-11eb-8b79-8aa27b2cd37b.mov
=> feat: add skills filter dropdown

src/course-search/ClearCurrentRefinements.jsx, src/course-search/CurrentRefinements.jsx, src/course-search/FacetItem.jsx, src/course-search/FacetListBase.jsx, src/course-search/SearchFilters.jsx, src/course-search/styles/_CurrentRefinements.scss, src/course-search/styles/_FacetList.scss, src/course-search/styles/_index.scss
A few things I missed yesterday, plus some updates to pills and chips.
Squares some corners, adds some padding to pills and chips, makes the buttons visible on the "default" variant.
"Inverse" variant
"default" variant
dropdown:
=> fix: update style variants

src/course-search/FacetItem.jsx, src/course-search/SearchBox.jsx, src/course-search/styles/_FacetList.scss
Note the pill is 4px shorter. Also, both the checkbox and pill are top-aligned to the facet item, rather than awkwardly being centered.
=> fix: clean up facet pill styles

src/course-search/config/index.js, src/course-search/data/tests/utils.test.js, src/course-search/data/utils.js
In order to appease `is-es5`, we need to replace the functionality of `query-string`'s `parse` method with the compatible `URLSearchParams` interface. In order to perfectly match behaviors, I've added a util function to convert the `URLSearchParams` object to a native dictionary.
=> fix: replacing query string parse with built in functionality

README.rst, package-lock.json, package.json, src/course-search/SearchContext.jsx, src/course-search/data/utils.js
In an effort to allow filter work to be es5 compatible, this PR is removing another instance of `query-string` which has presumably been causing headaches with polyfills.
=> fix: replacing query-string with built in functionality

package.json
`renderWithSearchContext` was being exported from `/utils/tests` but side effects were not disabled so our frontend apps were being bundled with all of the react test library
=> fix: disable side effects to not bundle all of the react testing library

.github/workflows/release.yml, package.json
On the first attempt to publish to the 3 packages to NPM, the running of lint, test, and build commands was previously only running packages that have changed since `origin/master` to avoid running things for packages that did not change.
However, since the refactor PR merged to `master`, the commit is equal with `origin/master` so Lerna deems that no changes have occurred:
Also, it turns out `lerna publish` does not accept the `--stream`` argument so this PR also removes that.
=> fix: updates to release config for Github Actions

.github/workflows/release.yml
On merge to `master`, we are seeing an error from `lerna publish` where it expects the Git author identity to be known. To fix this, I included a new Github Action `fregante/setup-git-user@v1` to update the git config with the Github Actions user. I wanted to try using this action before manually running the `git config` commands ourselves.
This is only needed for release.yml as ci.yml does not publish or call any git commands.
```
lerna ERR! Author identity unknown
lerna ERR! 
lerna ERR! *** Please tell me who you are.
lerna ERR! 
lerna ERR! Run
lerna ERR! 
lerna ERR!   git config --global user.email "you@example.com"
lerna ERR!   git config --global user.name "Your Name"
lerna ERR! 
lerna ERR! to set your account's default identity.
```
=> fix: add git author identity with setup-git-user action

.github/workflows/release.yml, packages/catalog-search/CHANGELOG.md, packages/catalog-search/package-lock.json, packages/catalog-search/package.json, packages/logistration/CHANGELOG.md, packages/logistration/package-lock.json, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package-lock.json, packages/utils/package.json
The previous merged PR incorrectly used the NPM commands meant for ci.yml, which tells Lerna to only run commands for packages that have changed since `origin/master`. This PR swaps back to running Lerna commands for all packages instead since once a PR is merged, it _is_ even with `origin/master` and won't release anything.
I deleted the most recent git tags Lerna created related to the last release attempt and reverted the previous "chore: publish" commit since Lerna should re-commit those changes once this PR is merged.
=> fix: run lerna commands for all packages regardless of whether they changed in release.yml

packages/catalog-search/__mocks__/react-instantsearch-dom.jsx, packages/catalog-search/src/tests/SearchFilters.test.jsx
Adds an algolia mock and a basic test that uses it. Should enable more conprehensive testing in the future!
=> test: add algolia mock and search filters test

packages/catalog-search/src/SearchBox.jsx
Adds the necessary tag for hotjar analytics.
Verified manually that the tag appears by using local `frontend-enterprise` on learner portal.
=> fix: add hotjar to searchbox

.github/workflows/release.yml
In our current release.yml workflow for Github Actions, the following commands are run:
1. `lerna version`
2. `lerna publish from-package`
`lerna version` tells Lerna to determine which packages changed and which versions they should be bumped to based on conventional commits. It then creates a "chore: publish" commit to bump versions in package.json files, add CHANGELOG entires, push Git tags, etc.
Then, the assumption was that `lerna publish from-package` would pull the correct version numbers from the updated/committed `package.json` files however this does not seem to be the case as Lerna is still attempting to publish over existing versions.
This PR swaps to using `lerna publish from-git` instead which theoretically should do a better job at actually adhering to the version number(s) …
=> ci: use from-git vs from-package in lerna publish

packages/logistration/src/LoginRedirect.jsx, packages/logistration/src/LoginRedirect.test.jsx
This PR is primarily a test of Lerna publishing now that we're using `lerna publish from-git`.
That said, this change is something I have in use locally (via module.config.js) for in-progress work related to Admin Portal login redirect behavior needing a way to display some custom UI while the user's account is being fetched.
=> fix: add loadingDisplay prop to LoginRedirect

.github/workflows/release.yml
This is an intermediate step in resolving Lerna publishing issues. On a previous merged PR, Lerna did not correctly publish the latest tagged version to NPM for `@edx/frontend-enterprise-logistration` which means the published NPM version is behind the versions specified in the Git tag or package.json file.
Temporarily changing `lerna publish` to use `from-package` will publish the changes from this version to NPM, at which point we can try a different approach.
=> ci: force publish from-package to get versions in sync with npm

packages/logistration/package-lock.json, packages/logistration/package.json, packages/utils/package-lock.json, packages/utils/package.json
After installing `@edx/frontend-enterprise-utils` and `@edx/frontend-enterprise-logistration` in `frontend-app-admin-portal`, a PR's CI began failing on the `npm run is-es5` check, noting that some bit of the minified vendors bundle contains non-ES5 compatible code that didn't get transpiled.
2 of the packages in this repo use `query-string@7` which is known to not be natively compatible with ES5. Per the docs, downgrading to `query-string@5` may help to resolve this issue.
=> fix: downgrade query-string to pin to ES5 compatible version

packages/catalog-search/src/index.js
[ENT4670](https://openedx.atlassian.net/browse/ENT-4670): This component is needed to use in the Skills-Quiz Dropdown.
Related PR:
https://github.com/edx/frontend-app-learner-portal-enterprise/pull/280
=> ENT4670: Exporting FacetListRefinement to use it in skills-quiz

packages/catalog-search/src/FacetListBase.jsx
Updated FacetListBase to save a list of the selected items even for `single-item` face-value-type.
At many places we assume that we will get a list of items, otherwise fails. to keep that consistent with the `array` type, setting the array with one value.
=> fix: Updated FacetListBase to save list of selected item

lerna.json, packages/catalog-search/__mocks__/react-instantsearch-dom.jsx, packages/catalog-search/src/ClearCurrentRefinements.jsx, packages/catalog-search/src/CurrentRefinements.jsx, packages/catalog-search/src/FacetListBase.jsx, packages/catalog-search/src/FacetListRefinement.jsx, packages/catalog-search/src/SearchContext.jsx, packages/catalog-search/src/SearchFilters.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/data/hooks.js, packages/catalog-search/src/data/tests/utils.test.js, packages/catalog-search/src/data/utils.js, packages/catalog-search/src/tests/CurrentRefinements.test.jsx, packages/catalog-search/src/tests/FacetListBase.test.jsx, packages/catalog-search/src/tests/FacetListRefinement.test.jsx, packages/catalog-search/src/tests/SearchContext.test.jsx
This PR refactors how the Algolia search refinements are synced with the URL query parameters, and fixes a bug where a refinement with a command in it would break the search results.
On initial page load, it parses the URL query parameters and applies them to the Algolia search refinements. However, previously, when a new refinement is selected, we would add it to the refinements reducer state and `SearchContext` would respond to this change, and attempt to update the query parameters.
This causes issues because the logic that parses the initial URL query parameters was also attempting to parse updates made to the query params when the refinements reducer changed. As a result, we were in a situation where these two bits of logic were conflicting and causing issues.
This PR updates this …
=> fix: improved support for lists of attribute values in Algolia facet filtering

.github/pull_request_template.md, .github/workflows/release.yml, README.rst
=> ci: release workflow should only increment versions

packages/catalog-search/src/FacetListBase.jsx, packages/catalog-search/src/SearchContext.jsx, packages/catalog-search/src/data/constants.js
The objective of this PR is to add more options to current Algolia widgets.
Newly added functionality in this PR:
1-Dropdown state in context was saved against attribute which can now be changed and saved against `customAttrbiute,` so multiple dropdowns can be loaded against the same attribute.
2- If it is desired to not refine the data from Algolia on the basis of user selection but only mark the checkboxes and save his selections.
3- Previously `SEARCH_FACET_FILTERS` selections were only saved as an array. Any other attributes value is saved as a string. Now if it is needed to save any other attribute value in the array then its key can be added in `ADDITIONAL_FACET_FILTERS.
https://openedx.atlassian.net/browse/ENT-4843
https://openedx.atlassian.net/browse/ENT-4844
Extra Details: …
=> feat: ENT4816- Add jobs dropdown

packages/catalog-search/package-lock.json, packages/logistration/package-lock.json, packages/logistration/src/LoginRedirect.jsx, packages/logistration/src/utils.js, packages/utils/package-lock.json, packages/utils/package.json, packages/utils/src/learnerPortalLinks.js
* Update `LoginRedirect` to support either an `enterpriseSlug` OR `enterpriseCustomerInviteKey` when redirecting to the proxy login page.
=> feat: support enterprise customer invite key in LoginRedirect

package-lock.json, package.json, packages/catalog-search/package.json, packages/catalog-search/src/FacetDropdown.jsx, packages/catalog-search/src/tests/SearchBox.test.jsx
This PR-
- updates to the latest paragon version
- makes facet dropdowns persist when clicking items
=> feat: persistent facet filters

.github/workflows/lockfileversion-check.yml
lockfileVersion for the package-lock.json generated by NPM6 was 1 but now as we've moved to Node16 and NPM8, package-lock.json should be generated using NPM8. lockfileVersion for package-lock.json generated using NPM8 is 2. So here we're going to check the lockfileVersion in package-lock.json
=> feat: Add package-lock file version check

.gitignore, package-lock.json, packages/catalog-search/package.json, packages/catalog-search/src/SearchFilters.jsx, packages/catalog-search/src/tests/SearchFilters.test.jsx, packages/logistration/package.json, packages/utils/package.json
ENT-5800.  Also installs react-responsive as a peer dependency.
Something about `useWindowSize()` from paragon isn't working quite right with the edx.org theme, so our original solution for https://2u-internal.atlassian.net/browse/ENT-5800 isn't working.  From Adam:
> I think the issue is that useWindowSize is including the extra width of the overflow facets in the total width. for example, at a window width of 1190px but useWindowSize says it's at 1249px, which is still above the breakpoint.
Note that there's still a little overrun from 1200px < screen width < ~1350px, but it's far better than before and I don't want to squish into the mobile view for reasonably-sized desktop browser windows by switching to the XL breakpoint.
- *Note*: This may be found in the …
=> fix: Use media query to resize for mobile in SearchFilters

README.rst, package-lock.json, package.json, packages/catalog-search/src/CurrentRefinements.jsx, packages/catalog-search/src/FacetListBase.jsx, packages/catalog-search/src/SearchBox.jsx, packages/catalog-search/src/SearchContext.jsx, packages/catalog-search/src/SearchFilters.jsx, packages/catalog-search/src/data/hooks.js, packages/hotjar/.eslintignore, packages/hotjar/.eslintrc.js, packages/hotjar/.gitignore, packages/hotjar/.npmignore, packages/hotjar/LICENSE, packages/hotjar/Makefile, packages/hotjar/README.rst, packages/hotjar/babel.config.js, packages/hotjar/jest.config.js, packages/hotjar/package.json, packages/hotjar/src/hotjar.js, packages/hotjar/src/tests/hotjar.test.js, packages/logistration/package.json, packages/utils/package.json
Add hotjar package so that we can move away from relying on `react-use-hotjar` which was causing dependency errors in our mfes. It will also give us control over hotjar functionality from now on.
Will need to go back, fix hook errors, and remove /* eslint-disable react-hooks/exhaustive-deps */ from files.
=> feat: add hotjar package

packages/catalog-search/src/FacetDropdown.jsx, packages/catalog-search/src/LearningTypeRadioFacet.jsx
Removes this annoying error in frontend-app-enterprise-public-catalog 
=> fix: small fix to dropdown toggle

packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/tests/SearchHeader.test.jsx
Fixes the issue where there is incorrectly a background color on the `SearchHeader` component used across 3 MFEs. 
- Dynamic theming was just recently-ish added to admin portal, so the `bg-brand-primary` class that was already on the `SearchHeader` component began to apply a style change once that class name had meaning within the admin portal MFE.
- It does not affect explore catalog because that MFE does need to support dynamic theming, so the class name there has no styles associated with it.
- In the learner portal, we use the `inverse` variant and actually _do_ want the background to be the enterprise's theme color. To keep support for learner portal, but fix for the other MFEs, the `bg-brand-primary` class will only be applied when `variant="inverse"`, which is only true for the …
=> fix: only apply bg-brand-primary to SearchHeader if variant=inverse

.github/workflows/release.yml
=> Try force pushing. Add static PR title/body

packages/catalog-search/src/styles/_SearchSuggestions.scss, packages/catalog-search/src/tests/SearchSuggestionItem.test.jsx
**Problem**: The typeahead in search on the explore catalog has some minor formatting/spacing  issues in course and program titles. the first two words in the title are mashed together and are both made bold. Just makes for some potentially confusing reading. 
**Solution**: Add `margin-left` to create a space between matching results. 
| Before |
| ------------- |
| <img width="991" alt="Screenshot 2023-05-30 at 11 55 15 AM" src="https://github.com/openedx/frontend-enterprise/assets/71999631/2be6b5c6-79d7-443d-b543-d2c1c2225c86">|  
| After |
| ------------- |
|<img width="985" alt="Screenshot 2023-05-30 at 11 51 16 AM" src="https://github.com/openedx/frontend-enterprise/assets/71999631/4d3cc126-0429-46f9-9d7e-76336a0d1782">|
Ticket Link
Link to the associated ticket
[Weird …
=> fix: missing space in search

package-lock.json, packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/logistration/CHANGELOG.md, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
- @edx/frontend-enterprise-catalog-search@4.2.0
- @edx/frontend-enterprise-logistration@3.2.0
- @edx/frontend-enterprise-utils@3.2.0
=> chore(release): publish new versions

README.rst, packages/catalog-search/src/SearchSuggestions.jsx, packages/catalog-search/src/data/constants.js, packages/catalog-search/src/tests/SearchSuggestions.test.jsx
__Jira Ticket:__ [ENT-7171](https://2u-internal.atlassian.net/browse/ENT-7171)
__Description:__
Executive Education redirects should point towards the learner portal when supported.
**Acceptance Criteria:** 
1. address [this](https://github.com/openedx/frontend-enterprise/pull/288/files#diff-14b69db7fa3f4c28463a4e2b2f228d220af050df013b750c0f039e15328b3d94R66-R67) todo within the frontend-enterprise utils package to allow for executive education suggested search to redirect to the enterprise learner portal.
Note that this will require updating the executive education section of the component’s usage of getLinkToCourse to account for the `executive-education-2u/course/<course_key>` learner portal route.
- *Note*: This may be found in the "Preview Updated Versions (dry …
=> ENT-7171: Updated course link for executive education courses.

package-lock.json, packages/catalog-search/package.json, packages/catalog-search/src/CurrentRefinements.jsx, packages/catalog-search/src/MobileFilterMenu.jsx, packages/catalog-search/src/SearchPagination.jsx, packages/catalog-search/src/styles/_CurrentRefinements.scss
This is part of a larger effort to deprecate Font Awesome in favor of solely using Paragon Icons, which will reduce bundle size and improve performance (page load time) since it’s a larger library. 
Replace all Font-awesome icons with Paragon icons. Before and after photos below:
`packages/catalog-search/src/CurrentRefinements.jsx`
| Before (Font-Awesome icons) | After (Paragon Icons)|
| ------------- | ------------- |
|<img width="345" alt="Screenshot 2023-08-02 at 11 45 34 PM" src="https://github.com/openedx/frontend-enterprise/assets/71999631/83d4cf08-a8fb-4948-ae2b-80f84181b852">|<img width="454" alt="Screenshot 2023-08-03 at 12 13 28 AM" src="https://github.com/openedx/frontend-enterprise/assets/71999631/37bdf7b7-b677-47bb-84fe-0f502fab42af">| …
=> chore: replace font-awesome with paragon icons

package-lock.json, packages/catalog-search/package.json, packages/catalog-search/src/SearchContext.jsx, packages/catalog-search/src/SearchSuggestionItem.jsx, packages/catalog-search/src/tests/CurrentRefinements.test.jsx, packages/catalog-search/src/tests/FacetListBase.test.jsx, packages/catalog-search/src/tests/FacetListRefinement.test.jsx, packages/catalog-search/src/tests/LearningTypeRadioFacet.test.jsx, packages/catalog-search/src/tests/SearchBox.test.jsx, packages/catalog-search/src/tests/SearchPagination.test.jsx, packages/catalog-search/src/tests/SearchSuggestionItem.test.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx, packages/hotjar/package.json, packages/logistration/package.json, packages/utils/package.json, packages/utils/src/test-utils.jsx
[React Router Upgrade to v6](https://github.com/openedx/platform-roadmap/issues/276).
This PR upgrades React Router from `v5` to `v6`.
- Upgrade `react-router-dom` from `v5` to `v6`
- Upgrade `frontend-platform` from `v4` to `v5`.
=> feat: upgrade react router to v6

package-lock.json, packages/catalog-search/package.json
Upgrades Paragon from v20 -> v21 (breaking change has no impact for `catalog-search`) in `devDependencies`; expands the `peerDependency` range to include v21.
=> feat: allow Paragon v21 in catalog-search

package-lock.json, packages/catalog-search/package.json, packages/logistration/package.json, packages/utils/package.json
This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.4`.
=> fix: bump frontend-platform

packages/catalog-search/src/LearningTypeRadioFacet.jsx, packages/catalog-search/src/SearchFilters.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/tests/LearningTypeRadioFacet.test.jsx
[Jira Ticket 
](https://2u-internal.atlassian.net/browse/ENT-8123)
We use a hardcoded list for Learning Type facet dropdown. This PR has new logic to block showing pathways on enterprise customers where the 'enablePathways' boolean is false. 
=> fix: remove pathways from customers search

package-lock.json, packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/catalog-search/src/LearningTypeRadioFacet.jsx, packages/catalog-search/src/SearchFilters.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/tests/LearningTypeRadioFacet.test.jsx, packages/logistration/CHANGELOG.md, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore(release): publish new versions 

packages/catalog-search/src/SearchBox.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/SearchSuggestionItem.jsx, packages/catalog-search/src/SearchSuggestions.jsx, packages/catalog-search/src/data/constants.js, packages/catalog-search/src/styles/_SearchSuggestions.scss, packages/catalog-search/src/tests/SearchHeader.test.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx
We want to add a prequery suggestions to the learner portal using the bayesian average that was [added to algolia](https://2u-internal.atlassian.net/browse/ENT-8193). The idea being when the course search box is focused, we give a drop down box selection of suggested courses based on their review data.
Related PR in learner portal: [#935](https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/935)
[JIRA](https://2u-internal.atlassian.net/browse/ENT-8194)
https://github.com/openedx/frontend-enterprise/assets/71999631/45803994-7294-427a-bdfc-c27f2d25e08c
- This may be triggered by clicking the "Run workflow" option for the …
=> feat: add prequery search suggestions

package-lock.json, packages/catalog-search/CHANGELOG.md, packages/catalog-search/package.json, packages/hotjar/CHANGELOG.md, packages/hotjar/package.json, packages/logistration/CHANGELOG.md, packages/logistration/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
- @edx/frontend-enterprise-catalog-search@6.0.0
- @edx/frontend-enterprise-hotjar@3.0.0
- @edx/frontend-enterprise-logistration@5.0.0
- @edx/frontend-enterprise-utils@5.0.0
=> chore(release): publish new versions for #367

packages/catalog-search/src/PrequerySearchSuggestionItem.jsx, packages/catalog-search/src/SearchBox.jsx, packages/catalog-search/src/SearchHeader.jsx, packages/catalog-search/src/SearchSuggestionItem.jsx, packages/catalog-search/src/SearchSuggestions.jsx, packages/catalog-search/src/tests/PrequerySearchSuggestionItem.test.jsx, packages/catalog-search/src/tests/SearchBox.test.jsx, packages/catalog-search/src/tests/SearchSuggestionItem.test.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx
Updated logic to ensure that prequery suggestions are only displayed for users in the variant group. 
https://2u-internal.atlassian.net/browse/ENT-8559 
=> feat: enable prequery suggestions only for variant group

packages/catalog-search/src/config/index.js, packages/catalog-search/src/data/constants.js, packages/catalog-search/src/data/tests/constants.test.js
Adds a "Subtitle" facet dropdown to the search header that corresponds to the `transcript_languages` attribute in Algolia to filter out the courses that have video transcripts associated with them.
[ENT-8400](https://2u-internal.atlassian.net/browse/ENT-8400)
=> [ENT-8400] Add subtitle facet to search header

package-lock.json, packages/catalog-search/package.json, packages/hotjar/package.json, packages/logistration/package.json, packages/utils/package.json
**Description**
- Major version upgrades, Updated `frontend-build` to v14 & Updated `frontend-platform` to v8
[Reference to respective MFEs with the build and platform major version upgrades to be released as minor versions instead of major ](https://github.com/openedx/frontend-component-header/pull/369#discussion_r1574802668)
=> feat: updated frontend-build & frontend-platform major versions

lerna.json
After re-creating the most recent Git tags to be associated with the `master` branch and the expected commit SHA, the `lerna version` command is not detecting changes for the most recent merged commit on `master`. The most recent commit updates package.json and package-lock.json versions, however, the `ignoreChanges` configuration in `lerna.json` included `package.json`, which prevents Lerna from detecting the most recent merged commit as a new change needing a version bump.
```shell
lerna info Looking for changed packages since @edx/frontend-enterprise-catalog-search@10.0.0
lerna info ignoring diff in paths matching [
lerna info ignoring diff in paths matching   'CHANGELOG.md',
lerna info ignoring diff in paths matching   'node_modules/**',
lerna info ignoring diff in paths matching …
```
=> chore: clean up ignoreChanges lerna config

README.rst
=> docs: minor updates to README release steps

.gitignore, Makefile, i18n/.gitkeep, package.json, packages/catalog-search/src/ClearCurrentRefinements.jsx, packages/catalog-search/src/CurrentRefinements.jsx, packages/catalog-search/src/FacetListBase.jsx, packages/catalog-search/src/LearningTypeRadioFacet.jsx, packages/catalog-search/src/MobileFilterMenu.jsx, packages/catalog-search/src/SearchBox.jsx, packages/catalog-search/src/SearchContext.jsx, packages/catalog-search/src/SearchPagination.jsx, packages/catalog-search/src/SearchSuggestions.jsx, packages/catalog-search/src/data/constants.js, packages/catalog-search/src/index.js, packages/catalog-search/src/tests/ClearCurrentRefinements.test.jsx, packages/catalog-search/src/tests/CurrentRefinements.test.jsx, packages/catalog-search/src/tests/FacetListBase.test.jsx, packages/catalog-search/src/tests/FacetListRefinement.test.jsx, packages/catalog-search/src/tests/MobileFilterMenu.test.jsx, packages/catalog-search/src/tests/SearchBox.test.jsx, packages/catalog-search/src/tests/SearchPagination.test.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx, packages/catalog-search/src/tests/utils.jsx, packages/catalog-search/src/utils.js
**Jira Ticket:** [ENT-8580](https://2u-internal.atlassian.net/browse/ENT-8580)
__Description:__
This PR adds i18n support for `catalog-search` package.
=> feat: Added scripts and marked strings for i18n.

packages/catalog-search/src/CurrentRefinements.jsx, packages/catalog-search/src/FacetItem.jsx, packages/catalog-search/src/messages.js
**Description:** Translate language, level and availability dropdown options.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-9146
=> feat: translate language, level and availability dropdown options

packages/catalog-search/src/LearningTypeRadioFacet.jsx, packages/catalog-search/src/config/index.js, packages/catalog-search/src/data/constants.js, packages/catalog-search/src/messages.js
**Description**
[Uploading Screen Recording 2024-07-09 at 8.33.02 PM.mov…](https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/86868918/120101a9-a8bc-4521-8d4d-0eb6bf16537d)
=> feat: added video in learning type facet

packages/catalog-search/src/LearningTypeRadioFacet.jsx, packages/catalog-search/src/data/constants.js
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-9791
**Description**
This PR adds a segment event to track the selected value from the learning type dropdown. This change is required for monitoring audience engagement with videos as part of feedback evaluation.
The event name and payload will be structured as follows:
**Event Name**: `edx.enterprise.learner_portal.catalog_search.learning_type_selected`
**Payload**: `{ learningType: 'course' }` 
The possible learning types are:
- course
- program
- learnerpathway
- video
- any
- *Note*: There …
=> [ENT-9791] Add segment event to track the selected value for "Learning Type" dropdown

.github/renovate.json
Updates renovate to attempt to create consolidated renovate PRs for each individual package (minor/patch) and individual PRs for major ugprades.
=> chore: consolidate renovate PRs per package

package-lock.json, packages/hotjar/package.json
=> feat: support React 18 in `@edx/frontend-enterprise-hotjar`

.github/workflows/release.yml, package-lock.json, packages/logistration/package.json
=> feat: support React 18 in `@edx/frontend-enterprise-logistration`

package-lock.json, packages/utils/package.json
BREAKING CHANGE: Requires @testing-library/react@^16 as a peer dependency
feat: support React 18
=> feat: support react 18 and move RTL to peerDep vs regular dep

package-lock.json, packages/catalog-search/package.json, packages/catalog-search/src/SearchPagination.jsx, packages/catalog-search/src/tests/ClearCurrentRefinements.test.jsx, packages/catalog-search/src/tests/CurrentRefinements.test.jsx, packages/catalog-search/src/tests/FacetListBase.test.jsx, packages/catalog-search/src/tests/FacetListRefinement.test.jsx, packages/catalog-search/src/tests/LearningTypeRadioFacet.test.jsx, packages/catalog-search/src/tests/MobileFilterMenu.test.jsx, packages/catalog-search/src/tests/SearchBox.test.jsx, packages/catalog-search/src/tests/SearchPagination.test.jsx, packages/catalog-search/src/tests/SearchSuggestionItem.test.jsx, packages/catalog-search/src/tests/SearchSuggestions.test.jsx
BREAKING CHANGE: drops support for @openedx/paragon v21 in favor of v22.
feat: support React 18
---
Fixes `Pagination` style bug in search:
=> feat: support React 18; drop support for Paragon v21 in favor of v22
